### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by keul** [collective/sc.contentrules.groupbydate#13]
The master code (unreleased) has better support for Dexterity content type.

@ericof, @hvelarde: can you provide a stable release?

**Comment by hvelarde** [comment]
I don't see any work on the master branch since 2014: https://github.com/collective/sc.contentrules.groupbydate/commits/master

**Comment by hvelarde** [comment]
now I see the problem: the release was made but the CHANGES.rst files was not updated:

https://pypi.python.org/pypi/sc.contentrules.groupbydate

**Comment by keul** [comment]
@hvelarde oh! My fault then. Tanks!
